version: '3.3'
services:
  dionaea:
    build: .
    container_name: dionaea
    ports:
      - "21:21"
      - "23:23"
      - "80:80"
      - "135:135"
      - "139:139"
      - "443:443"
      - "445:445"
      - "3306:3306"
      - "5060:5060"
      - "11211:11211"
    volumes:
      - ./dionaea_logs:/opt/dionaea/var/log/dionaea
    restart: unless-stopped